# Example GitHub Actions workflow demonstrating GitHub App token generation
# for use with declastruct-github
#
# .what = generates a GitHub App token for declastruct operations
# .why = GitHub Apps provide fine-grained permissions and avoid PAT limitations

name: provision-with-app-token

on:
  workflow_dispatch:
  push:
    paths:
      - 'provision/**'

jobs:
  # generate token from GitHub App
  tokens:
    runs-on: ubuntu-latest
    outputs:
      github-token: ${{ steps.app-token.outputs.token }}
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.DECLASTRUCT_GITHUB_APP_ID }}
          private-key: ${{ secrets.DECLASTRUCT_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

  # provision github resources using the app token
  provision:
    runs-on: ubuntu-latest
    needs: tokens
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Generate plan
        env:
          GITHUB_TOKEN: ${{ needs.tokens.outputs.github-token }}
        run: |
          npx declastruct plan \
            --wish ./provision/github.apps/resources.ts \
            --into ./plan.json

      - name: Apply plan
        env:
          GITHUB_TOKEN: ${{ needs.tokens.outputs.github-token }}
        run: |
          npx declastruct apply --plan ./plan.json
